import type { ContactInquiry } from "@/lib/contact";
import type { Locale } from "@/lib/i18n";

type Option<Value extends string> = { value: Value; label: string; hint?: string };

const es = {
  intro: "Un diagnóstico breve para entender el negocio antes de hablar de pantallas.",
  progress: "Pregunta",
  of: "de",
  selected: "seleccionadas",
  maxThree: "Elegí hasta tres opciones.",
  optional: "Opcional",
  notProvided: "No informado",
  continue: "Continuar",
  back: "Volver",
  review: "Revisar respuestas",
  edit: "Editar",
  submit: "Enviar diagnóstico",
  sending: "Enviando…",
  startOver: "Empezar otra consulta",
  keyboardHint: "Podés recorrer las opciones con Tab y seleccionar con la barra espaciadora.",
  browserOnly: "Tus respuestas permanecen en esta pantalla y no se transmiten hasta que confirmes el envío.",
  steps: {
    goal: {
      eyebrow: "01 · OBJETIVO",
      title: "¿Qué cambio tendría más impacto en tu negocio hoy?",
      helper: "Elegí el resultado principal. Después podemos ordenar objetivos secundarios.",
    },
    stage: {
      eyebrow: "02 · PUNTO DE PARTIDA",
      title: "¿Desde dónde estás empezando?",
      helper: "Esto define si conviene crear, reemplazar o evolucionar lo que ya existe.",
    },
    challenges: {
      eyebrow: "03 · DIAGNÓSTICO",
      title: "¿Qué sentís que está frenando el negocio?",
      helper: "Priorizá hasta tres frenos concretos, aunque todavía no sepas cómo resolverlos.",
    },
    audience: {
      eyebrow: "04 · RECORRIDO",
      title: "¿A quién necesitás convencer y qué debería hacer después?",
      helper: "No hace falta una definición perfecta: alcanza con describir a la persona o empresa más importante.",
    },
    brand: {
      eyebrow: "05 · PERCEPCIÓN",
      title: "¿Qué debería comunicar tu marca cuando alguien llega?",
      helper: "Elegí hasta tres sensaciones que deberían quedar claras antes de leer en detalle.",
    },
    needs: {
      eyebrow: "06 · SOLUCIÓN",
      title: "¿Qué tipo de ayuda estás buscando?",
      helper: "Podés combinar hasta tres. La solución final puede ser distinta si el diagnóstico lo pide.",
    },
    readiness: {
      eyebrow: "07 · CONTEXTO COMERCIAL",
      title: "¿Qué condiciones tenemos que contemplar para proponer algo realista?",
      helper: "La inversión actual no es un filtro: ayuda a entender el nivel de operación y podés no informarla.",
    },
    contact: {
      eyebrow: "08 · CONTACTO",
      title: "¿Con quién voy a conversar?",
      helper: "Sólo necesito los datos necesarios para responder esta consulta.",
    },
    context: {
      eyebrow: "09 · CONTEXTO ABIERTO",
      title: "¿Qué más debería saber antes de responderte?",
      helper: "Si hay algo más que pueda orientar la respuesta, podés contarlo acá. También podés dejar este paso vacío.",
    },
    review: {
      eyebrow: "10 · REVISIÓN",
      title: "Este es el mapa inicial de tu proyecto.",
      helper: "Revisalo antes de enviarlo. Podés volver a cualquier bloque sin perder lo que completaste.",
    },
  },
  fields: {
    website: "URL del sitio, tienda o producto actual",
    websiteHint: "Si existe, nos permite revisar el punto de partida.",
    audience: "Persona o empresa a la que querés llegar",
    desiredAction: "Acción principal que debería realizar",
    investment: "Inversión mensual actual en presencia digital, marketing o tecnología",
    timeline: "Plazo deseado",
    decisionStage: "Momento de decisión",
    name: "Nombre",
    email: "Email",
    company: "Empresa o proyecto",
    message: "Contexto adicional",
    other: "Contalo con tus palabras",
  },
  placeholders: {
    website: "https://…",
    audience: "Ej.: dueños de comercios que necesitan ordenar sus ventas online",
    name: "Tu nombre",
    email: "vos@empresa.com",
    company: "Opcional",
    message: "Qué ya intentaste, qué restricción existe o qué resultado te gustaría poder observar…",
    other: "Escribí una alternativa breve",
  },
  reviewLabels: {
    goal: "Objetivo",
    stage: "Punto de partida",
    challenges: "Frenos",
    audience: "Audiencia y acción",
    brand: "Marca",
    needs: "Ayuda buscada",
    readiness: "Contexto comercial",
    contact: "Contacto",
    context: "Contexto adicional",
  },
  validation: {
    chooseOne: "Elegí una opción para continuar.",
    chooseBetween: "Elegí entre una y tres opciones.",
    other: "Completá la alternativa que elegiste.",
    audience: "Completá una referencia breve sobre la audiencia.",
    name: "Ingresá al menos dos caracteres.",
    email: "Ingresá un email válido.",
    company: "El nombre es demasiado largo.",
    website: "Ingresá una URL completa que empiece con http:// o https://.",
    message: "El contexto adicional no puede superar los 3000 caracteres.",
  },
  privacyLead: "Al enviar, aceptás el tratamiento descripto en la",
  privacyAction: "política de privacidad.",
  success: "Tu diagnóstico fue entregado y quedó registrado. Gracias: ya tengo un punto de partida concreto para responderte.",
  providerError: "No pudimos entregar la consulta. Tus respuestas siguen en pantalla para que puedas reintentar.",
  disabled: {
    kicker: "RECORRIDO DE DEMOSTRACIÓN",
    title: "Podés completar y revisar todo el diagnóstico.",
    text: "La conexión segura con Google todavía requiere una autorización manual. Hasta entonces, el botón final permanece inactivo y ninguna respuesta sale de esta pantalla.",
    action: "Para avanzar ahora, usá el email directo que aparece arriba.",
    button: "Envío pendiente de activación",
  },
} as const;

const en = {
  intro: "A short diagnostic to understand the business before talking about screens.",
  progress: "Question",
  of: "of",
  selected: "selected",
  maxThree: "Choose up to three options.",
  optional: "Optional",
  notProvided: "Not provided",
  continue: "Continue",
  back: "Back",
  review: "Review answers",
  edit: "Edit",
  submit: "Send diagnostic",
  sending: "Sending…",
  startOver: "Start another inquiry",
  keyboardHint: "Use Tab to move through options and the space bar to select.",
  browserOnly: "Your answers remain on this screen and are not transmitted until you confirm the submission.",
  steps: {
    goal: { eyebrow: "01 · GOAL", title: "What change would have the greatest impact on your business today?", helper: "Choose the primary outcome. We can organize secondary goals later." },
    stage: { eyebrow: "02 · STARTING POINT", title: "Where are you starting from?", helper: "This helps determine whether to create, replace or evolve what already exists." },
    challenges: { eyebrow: "03 · DIAGNOSTIC", title: "What do you feel is holding the business back?", helper: "Prioritize up to three concrete blockers, even if you do not yet know how to solve them." },
    audience: { eyebrow: "04 · JOURNEY", title: "Who do you need to convince, and what should they do next?", helper: "It does not need to be perfect: describe the most important person or company." },
    brand: { eyebrow: "05 · PERCEPTION", title: "What should your brand communicate when someone arrives?", helper: "Choose up to three impressions that should be clear before anyone reads the details." },
    needs: { eyebrow: "06 · SOLUTION", title: "What kind of help are you looking for?", helper: "Combine up to three. The final solution may differ if the diagnostic points elsewhere." },
    readiness: { eyebrow: "07 · BUSINESS CONTEXT", title: "What conditions should a realistic proposal account for?", helper: "Current investment is not a filter: it signals operating context, and you may choose not to disclose it." },
    contact: { eyebrow: "08 · CONTACT", title: "Who will I be speaking with?", helper: "I only need the information required to answer this inquiry." },
    context: { eyebrow: "09 · OPEN CONTEXT", title: "What else should I know before replying?", helper: "If anything else could help shape the reply, add it here. You can also leave this step blank." },
    review: { eyebrow: "10 · REVIEW", title: "This is the initial map of your project.", helper: "Review it before sending. You can return to any block without losing your answers." },
  },
  fields: {
    website: "Current website, store or product URL",
    websiteHint: "If it exists, this lets me review the starting point.",
    audience: "Person or company you want to reach",
    desiredAction: "Primary action they should take",
    investment: "Current monthly investment in digital presence, marketing or technology",
    timeline: "Desired timing",
    decisionStage: "Decision stage",
    name: "Name",
    email: "Email",
    company: "Company or project",
    message: "Additional context",
    other: "Describe it in your own words",
  },
  placeholders: {
    website: "https://…",
    audience: "E.g. retail owners who need to organize online sales",
    name: "Your name",
    email: "you@company.com",
    company: "Optional",
    message: "What you have tried, what constraint exists, or what outcome you would like to observe…",
    other: "Write a short alternative",
  },
  reviewLabels: {
    goal: "Goal",
    stage: "Starting point",
    challenges: "Blockers",
    audience: "Audience and action",
    brand: "Brand",
    needs: "Help requested",
    readiness: "Business context",
    contact: "Contact",
    context: "Additional context",
  },
  validation: {
    chooseOne: "Choose an option to continue.",
    chooseBetween: "Choose between one and three options.",
    other: "Complete the alternative you selected.",
    audience: "Add a short reference about the audience.",
    name: "Enter at least two characters.",
    email: "Enter a valid email.",
    company: "The name is too long.",
    website: "Enter a complete URL starting with http:// or https://.",
    message: "Additional context cannot exceed 3000 characters.",
  },
  privacyLead: "By sending, you agree to the processing described in the",
  privacyAction: "privacy notice.",
  success: "Your diagnostic was delivered and recorded. Thank you: I now have a concrete starting point for my reply.",
  providerError: "I could not deliver the inquiry. Your answers remain on screen so you can try again.",
  disabled: {
    kicker: "DEMONSTRATION JOURNEY",
    title: "You can complete and review the entire diagnostic.",
    text: "The secure Google connection still requires manual authorization. Until then, the final button stays inactive and no answer leaves this screen.",
    action: "To move forward now, use the direct email shown above.",
    button: "Submission pending activation",
  },
} as const;

export const contactIntakeCopy = { es, en } as const satisfies Record<Locale, typeof es | typeof en>;

export const contactOptions = {
  es: {
    goals: [
      { value: "sell-more", label: "Vender más o mejorar la conversión" },
      { value: "qualified-leads", label: "Conseguir consultas más calificadas" },
      { value: "clarify-offer", label: "Explicar mejor la propuesta de valor" },
      { value: "build-trust", label: "Transmitir más confianza y profesionalismo" },
      { value: "streamline", label: "Ordenar o automatizar una operación" },
      { value: "validate", label: "Validar una idea o producto" },
      { value: "other", label: "Otro objetivo" },
    ],
    stages: [
      { value: "no-site", label: "Todavía no tengo sitio" },
      { value: "existing-underperforming", label: "Tengo un sitio, pero no genera el resultado esperado" },
      { value: "outdated-site", label: "Mi sitio quedó desactualizado o ya no representa la marca" },
      { value: "social-first", label: "Hoy vendo por redes, WhatsApp o marketplaces" },
      { value: "digital-product", label: "Ya existe un producto o sistema digital" },
      { value: "defining", label: "Todavía estoy definiendo el proyecto" },
    ],
    challenges: [
      { value: "unclear-offer", label: "La oferta no se entiende con claridad" },
      { value: "low-leads", label: "Llegan pocas consultas o no son calificadas" },
      { value: "low-conversion", label: "Hay visitas o interés, pero no convierten" },
      { value: "weak-brand", label: "La marca no se diferencia o no transmite confianza" },
      { value: "manual-ops", label: "Hay tareas manuales que frenan la operación" },
      { value: "tech-limits", label: "La tecnología o el mantenimiento ponen límites" },
      { value: "no-direction", label: "No sé qué priorizar ni por dónde empezar" },
      { value: "other", label: "Otro freno" },
    ],
    actions: [
      { value: "contact", label: "Contactar o dejar sus datos" },
      { value: "whatsapp", label: "Iniciar una conversación por WhatsApp" },
      { value: "buy", label: "Comprar" },
      { value: "book", label: "Reservar una reunión o turno" },
      { value: "quote", label: "Pedir una cotización" },
      { value: "register", label: "Registrarse o sumarse a una lista" },
      { value: "other", label: "Otra acción" },
    ],
    brandTraits: [
      { value: "trustworthy", label: "Confiable" },
      { value: "professional", label: "Profesional" },
      { value: "premium", label: "Premium" },
      { value: "clear", label: "Clara y simple" },
      { value: "innovative", label: "Innovadora" },
      { value: "human", label: "Cercana y humana" },
      { value: "bold", label: "Audaz y diferente" },
      { value: "other", label: "Otro atributo" },
    ],
    needs: [
      { value: "business-site", label: "Sitio institucional o landing page" },
      { value: "ecommerce", label: "E-commerce o experiencia de venta" },
      { value: "funnel", label: "Funnel o sistema de captación" },
      { value: "product", label: "MVP o producto digital" },
      { value: "evolution", label: "Rediseño o evolución de algo existente" },
      { value: "automation", label: "Integraciones o automatización" },
      { value: "strategy", label: "Diagnóstico y orientación estratégica" },
      { value: "other", label: "Otra necesidad" },
    ],
    investments: [
      { value: "none", label: "Todavía no estoy invirtiendo" },
      { value: "under-300", label: "Hasta USD 300 por mes" },
      { value: "300-1000", label: "Entre USD 300 y 1.000 por mes" },
      { value: "1000-3000", label: "Entre USD 1.000 y 3.000 por mes" },
      { value: "over-3000", label: "Más de USD 3.000 por mes" },
      { value: "prefer-not", label: "Prefiero no informarlo" },
    ],
    timelines: [
      { value: "asap", label: "Lo antes posible" },
      { value: "1-3-months", label: "Dentro de 1 a 3 meses" },
      { value: "3-6-months", label: "Dentro de 3 a 6 meses" },
      { value: "flexible", label: "Sin fecha fija / explorando" },
    ],
    decisionStages: [
      { value: "exploring", label: "Estoy explorando posibilidades" },
      { value: "needs-definition", label: "Necesito ayuda para definir el alcance" },
      { value: "partly-defined", label: "Ya tengo una idea bastante definida" },
      { value: "comparing", label: "Estoy comparando propuestas" },
      { value: "ready", label: "Estoy listo para empezar" },
    ],
  },
  en: {
    goals: [
      { value: "sell-more", label: "Sell more or improve conversion" },
      { value: "qualified-leads", label: "Generate more qualified inquiries" },
      { value: "clarify-offer", label: "Explain the value proposition more clearly" },
      { value: "build-trust", label: "Build trust and professional credibility" },
      { value: "streamline", label: "Organize or automate an operation" },
      { value: "validate", label: "Validate an idea or product" },
      { value: "other", label: "Another goal" },
    ],
    stages: [
      { value: "no-site", label: "I do not have a website yet" },
      { value: "existing-underperforming", label: "I have a site, but it is not delivering the expected outcome" },
      { value: "outdated-site", label: "My site is outdated or no longer represents the brand" },
      { value: "social-first", label: "I currently sell through social media, WhatsApp or marketplaces" },
      { value: "digital-product", label: "A digital product or system already exists" },
      { value: "defining", label: "I am still defining the project" },
    ],
    challenges: [
      { value: "unclear-offer", label: "The offer is not clearly understood" },
      { value: "low-leads", label: "There are too few inquiries or they are not qualified" },
      { value: "low-conversion", label: "There is traffic or interest, but it does not convert" },
      { value: "weak-brand", label: "The brand lacks differentiation or trust" },
      { value: "manual-ops", label: "Manual work is slowing the operation down" },
      { value: "tech-limits", label: "Technology or maintenance creates constraints" },
      { value: "no-direction", label: "I do not know what to prioritize or where to start" },
      { value: "other", label: "Another blocker" },
    ],
    actions: [
      { value: "contact", label: "Contact us or leave their details" },
      { value: "whatsapp", label: "Start a WhatsApp conversation" },
      { value: "buy", label: "Buy" },
      { value: "book", label: "Book a meeting or appointment" },
      { value: "quote", label: "Request a quote" },
      { value: "register", label: "Register or join a list" },
      { value: "other", label: "Another action" },
    ],
    brandTraits: [
      { value: "trustworthy", label: "Trustworthy" },
      { value: "professional", label: "Professional" },
      { value: "premium", label: "Premium" },
      { value: "clear", label: "Clear and simple" },
      { value: "innovative", label: "Innovative" },
      { value: "human", label: "Close and human" },
      { value: "bold", label: "Bold and distinctive" },
      { value: "other", label: "Another trait" },
    ],
    needs: [
      { value: "business-site", label: "Business website or landing page" },
      { value: "ecommerce", label: "E-commerce or sales experience" },
      { value: "funnel", label: "Funnel or lead-generation system" },
      { value: "product", label: "MVP or digital product" },
      { value: "evolution", label: "Redesign or evolution of something existing" },
      { value: "automation", label: "Integrations or automation" },
      { value: "strategy", label: "Diagnostic and strategic direction" },
      { value: "other", label: "Another need" },
    ],
    investments: [
      { value: "none", label: "I am not investing yet" },
      { value: "under-300", label: "Up to USD 300 per month" },
      { value: "300-1000", label: "USD 300–1,000 per month" },
      { value: "1000-3000", label: "USD 1,000–3,000 per month" },
      { value: "over-3000", label: "More than USD 3,000 per month" },
      { value: "prefer-not", label: "Prefer not to say" },
    ],
    timelines: [
      { value: "asap", label: "As soon as possible" },
      { value: "1-3-months", label: "Within 1–3 months" },
      { value: "3-6-months", label: "Within 3–6 months" },
      { value: "flexible", label: "No fixed date / exploring" },
    ],
    decisionStages: [
      { value: "exploring", label: "I am exploring possibilities" },
      { value: "needs-definition", label: "I need help defining scope" },
      { value: "partly-defined", label: "I already have a fairly defined idea" },
      { value: "comparing", label: "I am comparing proposals" },
      { value: "ready", label: "I am ready to start" },
    ],
  },
} as const satisfies Record<Locale, {
  goals: readonly Option<ContactInquiry["goal"]>[];
  stages: readonly Option<ContactInquiry["stage"]>[];
  challenges: readonly Option<ContactInquiry["challenges"][number]>[];
  actions: readonly Option<ContactInquiry["desiredAction"]>[];
  brandTraits: readonly Option<ContactInquiry["brandTraits"][number]>[];
  needs: readonly Option<ContactInquiry["needs"][number]>[];
  investments: readonly Option<ContactInquiry["investment"]>[];
  timelines: readonly Option<ContactInquiry["timeline"]>[];
  decisionStages: readonly Option<ContactInquiry["decisionStage"]>[];
}>;
