import type { Locale } from "@/lib/i18n";

export const publicContactEmail = "alegfink@gmail.com";

export const siteCopy = {
  es: {
    descriptor: "E-commerce y operaciones digitales | Producto, Growth, UX y ejecución asistida por IA",
    skip: "Saltar al contenido",
    nav: { work: "Proyectos", services: "Servicios", about: "Sobre mí", contact: "Contacto", menu: "Abrir menú" },
    common: {
      viewProject: "Ver proyecto",
      viewAll: "Ver los seis proyectos",
      visit: "Visitar proyecto",
      next: "Siguiente proyecto",
      role: "Mi rol",
      state: "Estado",
      year: "Fecha",
      stack: "Tecnología relevante",
      limits: "Estado y límites",
      outcomes: "Resultado verificable",
      decisions: "Decisiones clave",
      solution: "La solución",
      problem: "El punto de partida",
      evidence: "Evidencia del trabajo",
      contact: "Conversemos sobre el desafío",
      backHome: "Volver al inicio",
    },
    home: {
      metaTitle: "Alejandro Fink | E-commerce y operaciones digitales",
      metaDescription: "Portfolio de Alejandro Fink: e-commerce, producto, UX, Shopify, operaciones digitales y ejecución coordinada con IA o especialistas.",
      eyebrow: "E-commerce · Operaciones digitales · Producto",
      title: "Opero y hago avanzar negocios digitales conectando producto, experiencia y operación.",
      intro: "Conecto catálogo, Shopify, UX, marketing, atención, proveedores y logística. Traduzco necesidades comerciales en prioridades funcionales y coordino la ejecución técnica con IA o especialistas.",
      primaryCta: "Conversemos sobre el desafío",
      secondaryCta: "Ver proyectos",
      signal: "De la necesidad a una primera versión útil — con criterio, ejecución y límites claros.",
      featuredEyebrow: "Trabajo seleccionado · 01–03",
      featuredTitle: "Una promesa es más útil cuando la prueba está cerca.",
      featuredIntro: "Tres proyectos en distintos momentos: un negocio propio en producción, una solución operativa y un MVP de validación.",
      servicesEyebrow: "Áreas de trabajo · 04 frentes",
      servicesTitle: "Tecnología como medio de ejecución y validación",
      processEyebrow: "Cómo trabajo",
      processTitle: "Primero claridad. Después, una solución que se pueda usar.",
      processNote: "Los proyectos utilizan herramientas como React, TypeScript, Shopify, Storefront API, Supabase y Cloudflare D1. Mi rol es definir necesidades, prioridades y criterios, coordinar la implementación con IA o especialistas y validar el resultado funcional.",
      moreEyebrow: "Más trabajo · 04–06",
      moreTitle: "Funnel, high-ticket y una dirección editorial más humana.",
      perspectiveEyebrow: "Perspectiva",
      perspectiveTitle: "Del negocio a una solución operable",
      perspectiveText: "No parto de una tecnología. Parto del negocio, la audiencia, las restricciones y la próxima acción que la operación necesita habilitar. Defino prioridades, experiencia y criterios funcionales; después coordino la implementación y valido el resultado.",
      closingTitle: "¿Hay un desafío de e-commerce u operación digital que necesite avanzar?",
      closingText: "E-commerce, operaciones digitales, producto, experiencia de compra y coordinación de implementación para negocios, agencias o equipos.",
    },
    services: [
      { number: "01", title: "Operaciones de e-commerce y Shopify", text: "Catálogo, oferta, promociones, experiencia de compra, atención, pedidos, proveedores y coordinación logística." },
      { number: "02", title: "Producto, UX y experiencia de compra", text: "Investigación, arquitectura de información, recorridos, priorización, requisitos, criterios de aceptación y QA funcional." },
      { number: "03", title: "Coordinación de implementación digital", text: "Convierto necesidades comerciales en alcance ejecutable, coordino la resolución con IA o especialistas y valido el comportamiento esperado." },
      { number: "04", title: "Sitios, MVPs y evolución de soluciones", text: "Diseño y coordino soluciones funcionales para validar una propuesta, mejorar una operación o habilitar una próxima acción comercial." },
    ],
    process: [
      { number: "01", title: "Entender", text: "Negocio, audiencia, restricciones y objetivo antes de elegir la forma de la solución." },
      { number: "02", title: "Definir", text: "Alcance, recorrido, contenido y una primera versión útil que se pueda validar." },
      { number: "03", title: "Coordinar y ejecutar", text: "Organizo el alcance, coordino la implementación y reviso cada entrega contra los criterios acordados." },
      { number: "04", title: "Validar y evolucionar", text: "QA, medición y aprendizaje cuando el proyecto y la operación lo permiten." },
    ],
    workIndex: {
      metaTitle: "Proyectos — Alejandro Fink",
      metaDescription: "Seis proyectos de e-commerce, servicios, MVP, conversión y dirección editorial, con estado y límites explícitos.",
      eyebrow: "Archivo de trabajo · Seis proyectos",
      title: "Contextos distintos. La misma forma de unir negocio, experiencia y ejecución.",
      intro: "Los casos están ordenados por realidad operativa, amplitud de decisiones y evidencia disponible. Cada uno declara su estado sin confundir un prototipo público con un producto en producción.",
      closing: "¿Tu proyecto no entra en una categoría prolija? Mejor: empecemos por el problema.",
    },
    about: {
      metaTitle: "Sobre mí — Alejandro Fink",
      metaDescription: "Cómo Alejandro Fink conecta e-commerce, producto, UX y operaciones digitales para coordinar soluciones funcionales.",
      eyebrow: "Sobre mí",
      title: "Entender el negocio cambia lo que vale la pena construir.",
      lead: "Soy operador de e-commerce y coordinador de proyectos digitales. Conecto producto, experiencia, marketing y operación para convertir necesidades comerciales en soluciones funcionales.",
      paragraphs: [
        "Mi caso principal es Torvena, un e-commerce propio que opero de punta a punta: investigación y selección de productos, proveedores, catálogo, oferta, Shopify, creatividades, campañas, atención, pedidos y logística.",
        "También coordiné soluciones como Brisa do Mar, CUIDALO y otros sitios, propuestas y prototipos. En cada caso trabajo sobre el problema, la audiencia, el recorrido y el resultado que debe habilitarse.",
        "Uso IA para investigar, prototipar, implementar, conectar y diagnosticar. Puedo leer la lógica general del código, pero no programo ni depuro con autonomía: defino el resultado esperado, tomo decisiones funcionales y valido el comportamiento, recurriendo a herramientas o especialistas para la profundidad técnica.",
        "Me interesan colaboraciones en e-commerce operations, digital commerce, Shopify merchant operations, product operations y coordinación de implementación digital.",
      ],
      principlesTitle: "Principios de trabajo",
      principles: ["Claridad sobre decoración.", "Negocio sobre tecnología.", "Evidencia sobre claims.", "Una primera versión útil sobre complejidad anticipada."],
      collaborationTitle: "Dónde puedo aportar",
      collaborationText: "E-commerce, operaciones digitales, producto, experiencia de compra y coordinación de implementación para negocios, agencias o equipos.",
      graphic: {
        label: "Diagrama editorial de la práctica de Alejandro: negocio, experiencia y ejecución convergen en una solución útil.",
        kicker: "AF / Campo de trabajo",
        words: ["Negocio", "Experiencia", "Ejecución"],
        outcome: "Soluciones útiles",
      },
    },
    contact: {
      metaTitle: "Contacto — Alejandro Fink",
      metaDescription: "Conversemos sobre un desafío de e-commerce, operaciones digitales, producto, UX o implementación coordinada.",
      eyebrow: "Contacto",
      title: "Empecemos por el contexto, no por una lista de features.",
      intro: "Respondé un diagnóstico breve sobre el negocio, la marca y el punto de partida. El recorrido ayuda a convertir una necesidad difusa en una primera conversación concreta.",
      fitTitle: "Este espacio sirve para",
      fit: ["operaciones de e-commerce y Shopify", "producto, UX y experiencia de compra", "coordinación de implementación digital", "sitios, MVPs y evolución de soluciones", "colaboraciones con negocios, agencias o equipos"],
      directEyebrow: "Canal activo",
      directTitle: "¿Preferís avanzar ahora?",
      directText: "Podés abrir un mensaje nuevo directamente en Gmail o usar la aplicación de email que prefieras. El diagnóstico guiado de abajo reúne mejor el contexto comercial y evita pedirte una especificación técnica.",
      directAction: "Abrir en Gmail",
      directFallbackAction: "Usar otra app de email",
      directSubject: "Consulta desde el portfolio de Alejandro Fink",
      directBody: "Hola Alejandro,\n\nQuisiera conversar sobre un proyecto.",
      formEyebrow: "Diagnóstico inicial · 10 pasos",
      statusLabel: "Estado del contacto",
      enabledStatus: "Formulario activo",
      disabledStatus: "Diagnóstico activo · Envío pendiente",
    },
    privacy: {
      metaTitle: "Privacidad — Alejandro Fink",
      metaDescription: "Estado real del tratamiento de datos, contacto y medición en este portfolio.",
      eyebrow: "Privacidad · Estado actual",
      title: "Medimos lo que ayuda a mejorar el recorrido, sólo cuando vos lo aceptás.",
      updated: "Última actualización: 29 de agosto de 2026.",
      sections: [
        { title: "Contacto", text: "El portfolio ofrece enlaces directos a Gmail, email, WhatsApp, LinkedIn y GitHub. Al elegir un canal se abre el servicio correspondiente; el sitio no recibe ni almacena el nombre, email, teléfono o contenido del mensaje. Desde ese momento se aplican las prácticas de privacidad del canal elegido." },
        { title: "Finalidad y responsable", text: "Alejandro Fink usa los mensajes que decidas enviar exclusivamente para recibir, organizar y responder consultas profesionales. Podés contactarlo en alegfink@gmail.com." },
        { title: "Medición y consentimiento", text: "Google Analytics 4 se carga únicamente si elegís «Aceptar analítica». En ese caso registra páginas visitadas, procedencia y campañas UTM, dominio de referencia, país aproximado, idioma, navegador, sistema operativo, tipo de dispositivo, secciones y proyectos vistos, profundidad de lectura, canales de contacto elegidos y métricas de rendimiento como LCP, INP y CLS. No recibe nombres, emails, teléfonos ni contenido de mensajes. Google Signals, User-ID, personalización publicitaria y datos aportados por usuarios permanecen desactivados." },
        { title: "Campañas y atribución", text: "Los enlaces promocionales pueden incluir fuente, medio, campaña y pieza mediante parámetros UTM. Se conservan sólo valores saneados y nunca deben incluir nombres, emails, teléfonos, IDs personales ni texto libre. Esto permite comparar qué acciones acercan visitas e intención de contacto sin perfilar personas." },
        { title: "Servicios y acceso", text: "Las métricas consentidas se procesan en la propiedad de Google Analytics de Alejandro Fink. Sólo Alejandro y las cuentas de Google que él autorice pueden acceder a sus informes." },
        { title: "Conservación", text: "Los datos de usuarios y eventos de Google Analytics se configuran por 14 meses y el plazo no se reinicia ante nueva actividad; los informes agregados estándar pueden conservarse por más tiempo dentro del servicio. La elección de analítica queda guardada localmente hasta que la cambies." },
        { title: "Tus decisiones", text: "Podés rechazar analítica sin perder ninguna función y modificar la elección desde «Preferencias de analítica» en esta página. También podés solicitar información sobre el tratamiento escribiendo a alegfink@gmail.com." },
        { title: "Preferencia de idioma", text: "La elección ES/EN se guarda localmente en el navegador y en una cookie funcional para respetar la preferencia. No se utiliza para publicidad ni seguimiento entre sitios." },
        { title: "Enlaces externos", text: "Los casos pueden enlazar a sitios de terceros. Al visitarlos, sus propias prácticas y políticas pasan a aplicar." },
      ],
    },
    notFound: { eyebrow: "Error 404", title: "Esta página no forma parte del recorrido.", text: "Podés volver al inicio o recorrer los seis proyectos." },
    footer: { note: "E-commerce y operaciones digitales · Producto · UX · Ejecución asistida por IA", privacy: "Privacidad", language: "Idioma" },
  },
  en: {
    descriptor: "E-commerce & Digital Operations | Product, Growth, UX & AI-Assisted Execution",
    skip: "Skip to content",
    nav: { work: "Work", services: "Services", about: "About", contact: "Contact", menu: "Open menu" },
    common: {
      viewProject: "View project",
      viewAll: "View all six projects",
      visit: "Visit project",
      next: "Next project",
      role: "My role",
      state: "Status",
      year: "Date",
      stack: "Relevant technology",
      limits: "Current status and limits",
      outcomes: "Verified outcome",
      decisions: "Key decisions",
      solution: "The solution",
      problem: "The starting point",
      evidence: "Evidence of the work",
      contact: "Let’s discuss the challenge",
      backHome: "Back home",
    },
    home: {
      metaTitle: "Alejandro Fink | E-commerce & Digital Operations",
      metaDescription: "Alejandro Fink’s portfolio: e-commerce, product, UX, Shopify, digital operations and implementation coordinated with AI or specialists.",
      eyebrow: "E-commerce · Digital operations · Product",
      title: "I operate and move digital businesses forward by connecting product, experience and operations.",
      intro: "I connect catalog, Shopify, UX, marketing, customer experience, suppliers and fulfillment. I turn business needs into functional priorities and coordinate technical execution with AI or specialists.",
      primaryCta: "Let’s discuss the challenge",
      secondaryCta: "View my work",
      signal: "From a business need to a useful first version — with judgment, execution and clear limits.",
      featuredEyebrow: "Selected work · 01–03",
      featuredTitle: "A promise becomes useful when the proof is close by.",
      featuredIntro: "Three projects at different stages: an owned business in production, an operational solution and a validation MVP.",
      servicesEyebrow: "Areas of work · 04 fronts",
      servicesTitle: "Technology as a means of execution and validation",
      processEyebrow: "How I work",
      processTitle: "Clarity first. Then a solution people can actually use.",
      processNote: "Projects use tools such as React, TypeScript, Shopify, Storefront API, Supabase and Cloudflare D1. My role is to define needs, priorities and criteria, coordinate implementation with AI or specialists, and validate the functional outcome.",
      moreEyebrow: "More work · 04–06",
      moreTitle: "Funnels, high-ticket offers and a more human editorial direction.",
      perspectiveEyebrow: "Perspective",
      perspectiveTitle: "From the business need to an operable solution",
      perspectiveText: "I do not start with a technology. I start with the business, the audience, the constraints and the next action the operation needs to enable. I define priorities, experience and functional criteria, then coordinate implementation and validate the outcome.",
      closingTitle: "Is there an e-commerce or digital operations challenge that needs to move forward?",
      closingText: "E-commerce, digital operations, product, purchase experience and implementation coordination for businesses, agencies or teams.",
    },
    services: [
      { number: "01", title: "E-commerce and Shopify operations", text: "Catalog, offer, promotions, purchase experience, customer support, orders, suppliers and fulfillment coordination." },
      { number: "02", title: "Product, UX and purchase experience", text: "Research, information architecture, user flows, prioritization, requirements, acceptance criteria and functional QA." },
      { number: "03", title: "Digital implementation coordination", text: "I turn business needs into executable scope, coordinate delivery with AI or specialists and validate the expected behavior." },
      { number: "04", title: "Websites, MVPs and solution evolution", text: "I design and coordinate functional solutions to validate an offer, improve an operation or enable the next commercial action." },
    ],
    process: [
      { number: "01", title: "Understand", text: "Business, audience, constraints and goal before choosing the shape of the solution." },
      { number: "02", title: "Define", text: "Scope, journey, content and a useful first version that can be validated." },
      { number: "03", title: "Coordinate and execute", text: "I organize scope, coordinate implementation and review each delivery against the agreed criteria." },
      { number: "04", title: "Validate and evolve", text: "QA, measurement and learning when the project and operation make it possible." },
    ],
    workIndex: {
      metaTitle: "Work — Alejandro Fink",
      metaDescription: "Six e-commerce, service, MVP, conversion and editorial projects, each with explicit status and limits.",
      eyebrow: "Work archive · Six projects",
      title: "Different contexts. The same way of connecting business, experience and execution.",
      intro: "Projects are ordered by operational reality, breadth of decisions and available evidence. Each declares its status without mistaking a public prototype for a production product.",
      closing: "Does your project resist a neat category? Good — let’s start with the problem.",
    },
    about: {
      metaTitle: "About — Alejandro Fink",
      metaDescription: "How Alejandro Fink connects e-commerce, product, UX and digital operations to coordinate functional solutions.",
      eyebrow: "About",
      title: "Understanding the business changes what is worth building.",
      lead: "I am an e-commerce operator and digital project coordinator. I connect product, experience, marketing and operations to turn business needs into functional solutions.",
      paragraphs: [
        "My main case is Torvena, an e-commerce business I operate end to end: product research and selection, suppliers, catalog, offer, Shopify, creatives, campaigns, customer support, orders and fulfillment.",
        "I have also coordinated solutions such as Brisa do Mar, CUIDALO and other websites, proposals and prototypes. In each case, I work from the problem, audience, journey and outcome the solution needs to enable.",
        "I use AI to research, prototype, implement, connect and diagnose. I can read the general logic of code, but I do not program or debug autonomously: I define the expected outcome, make functional decisions and validate behavior, relying on tools or specialists for technical depth.",
        "I am interested in e-commerce operations, digital commerce, Shopify merchant operations, product operations and digital implementation coordination.",
      ],
      principlesTitle: "Working principles",
      principles: ["Clarity over decoration.", "Business over technology.", "Evidence over claims.", "A useful first version over anticipated complexity."],
      collaborationTitle: "Where I can contribute",
      collaborationText: "E-commerce, digital operations, product, purchase experience and implementation coordination for businesses, agencies or teams.",
      graphic: {
        label: "Editorial diagram of Alejandro’s practice: business, experience and execution converge into a useful solution.",
        kicker: "AF / Field of practice",
        words: ["Business", "Experience", "Execution"],
        outcome: "Useful solutions",
      },
    },
    contact: {
      metaTitle: "Contact — Alejandro Fink",
      metaDescription: "Let’s discuss an e-commerce, digital operations, product, UX or coordinated implementation challenge.",
      eyebrow: "Contact",
      title: "Let’s start with context, not a feature list.",
      intro: "Answer a short diagnostic about the business, brand and starting point. The journey turns a broad need into a concrete first conversation.",
      fitTitle: "This space is for",
      fit: ["e-commerce and Shopify operations", "product, UX and purchase experience", "digital implementation coordination", "websites, MVPs and solution evolution", "collaboration with businesses, agencies or teams"],
      directEyebrow: "Active channel",
      directTitle: "Would you rather move forward now?",
      directText: "Open a new message directly in Gmail or use whichever email app you prefer. The guided diagnostic below captures business context without asking you for a technical specification.",
      directAction: "Open in Gmail",
      directFallbackAction: "Use another email app",
      directSubject: "Inquiry from Alejandro Fink's portfolio",
      directBody: "Hi Alejandro,\n\nI would like to discuss a project.",
      formEyebrow: "Initial diagnostic · 10 steps",
      statusLabel: "Contact status",
      enabledStatus: "Form active",
      disabledStatus: "Diagnostic active · Submission pending",
    },
    privacy: {
      metaTitle: "Privacy — Alejandro Fink",
      metaDescription: "The current state of data processing, contact and measurement on this portfolio.",
      eyebrow: "Privacy · Current state",
      title: "We measure what helps improve the journey, only when you accept.",
      updated: "Last updated: August 29, 2026.",
      sections: [
        { title: "Contact", text: "The portfolio provides direct links to Gmail, email, WhatsApp, LinkedIn and GitHub. Choosing a channel opens the corresponding service; the site does not receive or store your name, email, phone number or message content. From that point, the selected channel’s privacy practices apply." },
        { title: "Purpose and controller", text: "Alejandro Fink uses any message you choose to send exclusively to receive, organize and respond to professional inquiries. You can contact him at alegfink@gmail.com." },
        { title: "Measurement and consent", text: "Google Analytics 4 loads only after you choose “Accept analytics”. It then records visited pages, acquisition and UTM campaigns, referring domain, approximate country, language, browser, operating system, device type, viewed sections and projects, reading depth, selected contact channels and performance metrics such as LCP, INP and CLS. It never receives names, emails, phone numbers or message content. Google Signals, User-ID, advertising personalization and user-provided data remain disabled." },
        { title: "Campaigns and attribution", text: "Promotional links may include source, medium, campaign and creative through UTM parameters. Only sanitized values are kept, and they must never contain names, emails, phone numbers, personal IDs or free text. This makes it possible to compare which actions produce visits and contact intent without profiling individuals." },
        { title: "Services and access", text: "Consented metrics are processed in Alejandro Fink’s Google Analytics property. Only Alejandro and the Google accounts he authorizes can access its reports." },
        { title: "Retention", text: "Google Analytics user and event data is configured for 14 months without resetting the period on new activity; standard aggregate reports may remain available longer within the service. Your analytics choice is stored locally until you change it." },
        { title: "Your choices", text: "You can reject analytics without losing any feature and change your choice from “Analytics preferences” on this page. You may also request information about the processing by writing to alegfink@gmail.com." },
        { title: "Language preference", text: "The ES/EN choice is stored locally in the browser and in a functional cookie so the preference can be respected. It is not used for advertising or cross-site tracking." },
        { title: "External links", text: "Case studies may link to third-party sites. Their own practices and policies apply when you visit them." },
      ],
    },
    notFound: { eyebrow: "Error 404", title: "This page is not part of the journey.", text: "You can return home or explore all six projects." },
    footer: { note: "E-commerce & digital operations · Product · UX · AI-assisted execution", privacy: "Privacy", language: "Language" },
  },
} as const satisfies Record<Locale, unknown>;

export type SiteCopy = (typeof siteCopy)[Locale];
