import type { Locale } from "@/lib/i18n";

export const publicContactEmail = "alegfink@gmail.com";

export const siteCopy = {
  es: {
    descriptor: "Desarrollador web y creador de productos digitales",
    skip: "Saltar al contenido",
    nav: { work: "Proyectos", services: "Servicios", about: "Sobre mí", contact: "Contacto", menu: "Abrir menú" },
    common: {
      viewProject: "Ver proyecto",
      viewAll: "Ver los seis proyectos",
      visit: "Visitar proyecto",
      next: "Siguiente proyecto",
      role: "Mi rol",
      state: "Estado",
      year: "Fecha",
      stack: "Tecnología relevante",
      limits: "Estado y límites",
      outcomes: "Resultado verificable",
      decisions: "Decisiones clave",
      solution: "Qué construí",
      problem: "El punto de partida",
      evidence: "Evidencia del trabajo",
      contact: "Contame tu proyecto",
      backHome: "Volver al inicio",
    },
    home: {
      metaTitle: "Alejandro Fink — Desarrollo web con criterio de negocio",
      metaDescription: "Sitios web, e-commerce y productos digitales diseñados y construidos para resolver necesidades reales de negocio.",
      eyebrow: "Desarrollo web · UX · Producto",
      title: "Diseño y desarrollo sitios web y productos digitales que resuelven problemas reales de negocio.",
      intro: "Combino desarrollo, experiencia de usuario y criterio comercial para convertir ideas, operaciones y oportunidades en soluciones web funcionales.",
      primaryCta: "Contame tu proyecto",
      secondaryCta: "Ver proyectos",
      signal: "De la necesidad a una primera versión útil — con criterio, ejecución y límites claros.",
      featuredEyebrow: "Trabajo seleccionado · 01–03",
      featuredTitle: "Una promesa es más útil cuando la prueba está cerca.",
      featuredIntro: "Tres proyectos en distintos momentos: un negocio propio en producción, una solución operativa y un MVP de validación.",
      servicesEyebrow: "Qué puedo construir · 04 frentes",
      servicesTitle: "La tecnología empieza después de entender qué necesita cambiar.",
      processEyebrow: "Cómo trabajo",
      processTitle: "Primero claridad. Después, una solución que se pueda usar.",
      processNote: "Uso IA para acelerar investigación, prototipado, desarrollo e iteración. La estrategia, el criterio y la validación siguen siendo humanos.",
      moreEyebrow: "Más trabajo · 04–06",
      moreTitle: "Funnel, high-ticket y una dirección editorial más humana.",
      perspectiveEyebrow: "Perspectiva",
      perspectiveTitle: "Construyo con la mirada de quien también vende y opera.",
      perspectiveText: "Mi base full stack se cruza con experiencia en ventas consultivas, UX, producto y desarrollo asistido por IA. Operar Torvena sumó una capa decisiva: convivir con catálogo, adquisición, soporte, logística y mejora continua, no solo con la interfaz.",
      closingTitle: "¿Hay una necesidad de negocio que una mejor experiencia web podría destrabar?",
      closingText: "Podemos ordenar el problema, definir una primera versión útil y decidir qué vale la pena construir ahora.",
    },
    services: [
      { number: "01", title: "Sitios de negocio y landing pages", text: "Clarificar una oferta, organizar el recorrido y convertir atención en una próxima acción concreta." },
      { number: "02", title: "E-commerce y experiencias de venta", text: "Conectar catálogo, contenido, confianza y operación dentro de un canal de venta propio." },
      { number: "03", title: "MVPs y productos digitales", text: "Transformar una oportunidad en una primera versión que permita observar uso, intención y límites reales." },
      { number: "04", title: "Soluciones a medida y evolución", text: "Extender productos existentes con flujos, paneles, integraciones y mejoras apoyadas en evidencia." },
    ],
    process: [
      { number: "01", title: "Entender", text: "Negocio, audiencia, restricciones y objetivo antes de elegir la forma de la solución." },
      { number: "02", title: "Definir", text: "Alcance, recorrido, contenido y una primera versión útil que se pueda validar." },
      { number: "03", title: "Diseñar y construir", text: "Interfaz, desarrollo e integraciones trabajando como un solo sistema." },
      { number: "04", title: "Validar y evolucionar", text: "QA, medición y aprendizaje cuando el proyecto y la operación lo permiten." },
    ],
    workIndex: {
      metaTitle: "Proyectos — Alejandro Fink",
      metaDescription: "Seis proyectos de e-commerce, servicios, MVP, conversión y dirección editorial, con estado y límites explícitos.",
      eyebrow: "Archivo de trabajo · Seis proyectos",
      title: "Contextos distintos. La misma forma de unir negocio, experiencia y ejecución.",
      intro: "Los casos están ordenados por realidad operativa, amplitud de decisiones y evidencia disponible. Cada uno declara su estado sin confundir un prototipo público con un producto en producción.",
      closing: "¿Tu proyecto no entra en una categoría prolija? Mejor: empecemos por el problema.",
    },
    about: {
      metaTitle: "Sobre mí — Alejandro Fink",
      metaDescription: "Cómo Alejandro Fink combina desarrollo, UX, experiencia comercial y operación para construir soluciones web útiles.",
      eyebrow: "Sobre mí",
      title: "Entender el negocio cambia lo que vale la pena construir.",
      lead: "Soy desarrollador web y creador de productos digitales. Mi trabajo vive en el cruce entre construcción técnica, experiencia de usuario y criterio comercial.",
      paragraphs: [
        "La formación full stack me dio una base para convertir decisiones en sistemas funcionales. La experiencia en ventas consultivas me enseñó a escuchar mejor el problema, detectar objeciones y no confundir una feature con una razón para comprar.",
        "UX, producto y desarrollo asistido por IA ampliaron ese proceso. Uso las herramientas para investigar, prototipar y construir con más alcance, mientras mantengo el criterio, la validación y la responsabilidad sobre lo que se publica.",
        "Torvena terminó de volver esta mirada operativa: además de construir el storefront, trabajo con catálogo, oferta, campañas, soporte, logística y mejora continua. Esa cercanía con la operación influye en cada solución que diseño.",
      ],
      principlesTitle: "Principios de trabajo",
      principles: ["Claridad sobre decoración.", "Negocio sobre tecnología.", "Evidencia sobre claims.", "Una primera versión útil sobre complejidad anticipada."],
      collaborationTitle: "Dónde puedo aportar",
      collaborationText: "Proyectos directos con dueños y equipos de negocio, colaboración con agencias o consultoras, y trabajo contract cuando el desafío requiere autonomía de producto y ejecución web.",
      graphic: {
        label: "Diagrama editorial de la práctica de Alejandro: negocio, experiencia y ejecución convergen en una solución útil.",
        kicker: "AF / Campo de trabajo",
        words: ["Negocio", "Experiencia", "Ejecución"],
        outcome: "Soluciones útiles",
      },
    },
    contact: {
      metaTitle: "Contacto — Alejandro Fink",
      metaDescription: "Contale a Alejandro el contexto de tu sitio, e-commerce, MVP o producto digital.",
      eyebrow: "Contacto",
      title: "Empecemos por el contexto, no por una lista de features.",
      intro: "Respondé un diagnóstico breve sobre el negocio, la marca y el punto de partida. El recorrido ayuda a convertir una necesidad difusa en una primera conversación concreta.",
      fitTitle: "Este espacio sirve para",
      fit: ["sitios de negocio y landing pages", "e-commerce y experiencias de venta", "MVPs y productos digitales", "evolución de productos existentes", "colaboraciones con agencias o equipos contract"],
      directEyebrow: "Canal activo",
      directTitle: "¿Preferís avanzar ahora?",
      directText: "Podés abrir un mensaje nuevo directamente en Gmail o usar la aplicación de email que prefieras. El diagnóstico guiado de abajo reúne mejor el contexto comercial y evita pedirte una especificación técnica.",
      directAction: "Abrir en Gmail",
      directFallbackAction: "Usar otra app de email",
      directSubject: "Consulta desde el portfolio de Alejandro Fink",
      directBody: "Hola Alejandro,\n\nQuisiera conversar sobre un proyecto.",
      formEyebrow: "Diagnóstico inicial · 10 pasos",
      statusLabel: "Estado del contacto",
      enabledStatus: "Formulario activo",
      disabledStatus: "Diagnóstico activo · Envío pendiente",
    },
    privacy: {
      metaTitle: "Privacidad — Alejandro Fink",
      metaDescription: "Estado real del tratamiento de datos, contacto y medición en este portfolio.",
      eyebrow: "Privacidad · Estado actual",
      title: "El formulario usa sólo los datos necesarios para responderte. Analytics sigue desactivado.",
      updated: "Última actualización: 10 de agosto de 2026.",
      sections: [
        { title: "Diagnóstico de contacto", text: "Podés recorrer el diagnóstico sin que las respuestas salgan de la pantalla. Si finalmente lo enviás, se procesan los datos que completaste: objetivo principal, punto de partida, frenos, audiencia, acción buscada, atributos de marca, soluciones de interés, rango de inversión actual —incluida la opción de no informarlo—, plazo, etapa de decisión, nombre, email, empresa opcional, URL opcional, idioma y contexto adicional opcional. No se guarda tu IP ni información del navegador en la bandeja de consultas." },
        { title: "Finalidad y responsable", text: "Alejandro Fink usa estos datos exclusivamente para recibir, organizar y responder consultas profesionales. Podés contactarlo en alegfink@gmail.com." },
        { title: "Servicios y acceso", text: "El sitio transmite la consulta a una aplicación de Google Apps Script. Se registra en una hoja privada de Google Sheets y se envía una notificación mediante Google Mail. Sólo Alejandro tiene acceso operativo a esa bandeja." },
        { title: "Conservación", text: "Las consultas se conservan como máximo durante 12 meses desde su recepción y se eliminan antes si ya no son necesarias. El seguimiento y la eliminación se realizan manualmente." },
        { title: "Tus decisiones", text: "Podés pedir acceso, corrección o eliminación de una consulta escribiendo a alegfink@gmail.com. También podés usar el email directo sin completar el formulario." },
        { title: "Medición", text: "Existe un contrato técnico de eventos, pero no hay un proveedor de analytics instalado. No se registran eventos, contenido de formularios ni datos personales por defecto." },
        { title: "Preferencia de idioma", text: "La elección ES/EN se guarda localmente en el navegador y en una cookie funcional para respetar la preferencia. No se utiliza para publicidad ni seguimiento entre sitios." },
        { title: "Enlaces externos", text: "Los casos pueden enlazar a sitios de terceros. Al visitarlos, sus propias prácticas y políticas pasan a aplicar." },
      ],
    },
    notFound: { eyebrow: "Error 404", title: "Esta página no forma parte del recorrido.", text: "Podés volver al inicio o recorrer los seis proyectos." },
    footer: { note: "Desarrollo web con criterio de negocio.", privacy: "Privacidad", language: "Idioma" },
  },
  en: {
    descriptor: "Web Developer & Digital Product Builder",
    skip: "Skip to content",
    nav: { work: "Work", services: "Services", about: "About", contact: "Contact", menu: "Open menu" },
    common: {
      viewProject: "View project",
      viewAll: "View all six projects",
      visit: "Visit project",
      next: "Next project",
      role: "My role",
      state: "Status",
      year: "Date",
      stack: "Relevant technology",
      limits: "Current status and limits",
      outcomes: "Verified outcome",
      decisions: "Key decisions",
      solution: "What I built",
      problem: "The starting point",
      evidence: "Evidence of the work",
      contact: "Tell me about your project",
      backHome: "Back home",
    },
    home: {
      metaTitle: "Alejandro Fink — Business-minded web development",
      metaDescription: "Websites, e-commerce experiences and digital products designed and built to solve real business needs.",
      eyebrow: "Web development · UX · Product",
      title: "I design and build websites and digital products that solve real business problems.",
      intro: "I combine development, user experience, and commercial thinking to turn ideas, operations, and opportunities into functional web solutions.",
      primaryCta: "Tell me about your project",
      secondaryCta: "View my work",
      signal: "From a business need to a useful first version — with judgment, execution and clear limits.",
      featuredEyebrow: "Selected work · 01–03",
      featuredTitle: "A promise becomes useful when the proof is close by.",
      featuredIntro: "Three projects at different stages: an owned business in production, an operational solution and a validation MVP.",
      servicesEyebrow: "What I can build · 04 fronts",
      servicesTitle: "Technology comes after understanding what needs to change.",
      processEyebrow: "How I work",
      processTitle: "Clarity first. Then a solution people can actually use.",
      processNote: "I use AI to accelerate research, prototyping, development and iteration. Strategy, judgment and validation remain human.",
      moreEyebrow: "More work · 04–06",
      moreTitle: "Funnels, high-ticket offers and a more human editorial direction.",
      perspectiveEyebrow: "Perspective",
      perspectiveTitle: "I build with the perspective of someone who also sells and operates.",
      perspectiveText: "My full-stack foundation overlaps with consultative sales, UX, product and AI-assisted development. Operating Torvena added a decisive layer: working with catalog, acquisition, support, logistics and continuous improvement — not only the interface.",
      closingTitle: "Could a better web experience unlock a real business need?",
      closingText: "We can frame the problem, define a useful first version and decide what is worth building now.",
    },
    services: [
      { number: "01", title: "Business websites and landing pages", text: "Clarify an offer, shape the journey and turn attention into a concrete next step." },
      { number: "02", title: "E-commerce and sales experiences", text: "Connect catalog, content, trust and operations inside an owned sales channel." },
      { number: "03", title: "MVPs and digital products", text: "Turn an opportunity into a first version that can reveal usage, intent and real constraints." },
      { number: "04", title: "Custom solutions and product evolution", text: "Extend existing products with flows, dashboards, integrations and evidence-led improvements." },
    ],
    process: [
      { number: "01", title: "Understand", text: "Business, audience, constraints and goal before choosing the shape of the solution." },
      { number: "02", title: "Define", text: "Scope, journey, content and a useful first version that can be validated." },
      { number: "03", title: "Design and build", text: "Interface, development and integrations working as one system." },
      { number: "04", title: "Validate and evolve", text: "QA, measurement and learning when the project and operation make it possible." },
    ],
    workIndex: {
      metaTitle: "Work — Alejandro Fink",
      metaDescription: "Six e-commerce, service, MVP, conversion and editorial projects, each with explicit status and limits.",
      eyebrow: "Work archive · Six projects",
      title: "Different contexts. The same way of connecting business, experience and execution.",
      intro: "Projects are ordered by operational reality, breadth of decisions and available evidence. Each declares its status without mistaking a public prototype for a production product.",
      closing: "Does your project resist a neat category? Good — let’s start with the problem.",
    },
    about: {
      metaTitle: "About — Alejandro Fink",
      metaDescription: "How Alejandro Fink combines development, UX, commercial experience and operations to build useful web solutions.",
      eyebrow: "About",
      title: "Understanding the business changes what is worth building.",
      lead: "I’m a web developer and digital product builder. My work sits at the intersection of technical execution, user experience and commercial thinking.",
      paragraphs: [
        "A full-stack foundation gave me the means to turn decisions into functional systems. Consultative sales taught me to listen more closely to the problem, recognize objections and avoid confusing a feature with a reason to buy.",
        "UX, product thinking and AI-assisted development expanded that process. I use the tools to research, prototype and build with greater range while retaining judgment, validation and responsibility for what gets published.",
        "Torvena made this perspective operational: beyond the storefront, I work with catalog, offers, campaigns, support, logistics and continuous improvement. That proximity to the operation shapes every solution I design.",
      ],
      principlesTitle: "Working principles",
      principles: ["Clarity over decoration.", "Business over technology.", "Evidence over claims.", "A useful first version over anticipated complexity."],
      collaborationTitle: "Where I can contribute",
      collaborationText: "Direct projects with owners and business teams, collaboration with agencies or consultancies, and contract work when the challenge calls for product autonomy and web execution.",
      graphic: {
        label: "Editorial diagram of Alejandro’s practice: business, experience and execution converge into a useful solution.",
        kicker: "AF / Field of practice",
        words: ["Business", "Experience", "Execution"],
        outcome: "Useful solutions",
      },
    },
    contact: {
      metaTitle: "Contact — Alejandro Fink",
      metaDescription: "Share the context behind your website, e-commerce, MVP or digital product with Alejandro.",
      eyebrow: "Contact",
      title: "Let’s start with context, not a feature list.",
      intro: "Answer a short diagnostic about the business, brand and starting point. The journey turns a broad need into a concrete first conversation.",
      fitTitle: "This space is for",
      fit: ["business websites and landing pages", "e-commerce and sales experiences", "MVPs and digital products", "evolution of existing products", "agency and contract collaborations"],
      directEyebrow: "Active channel",
      directTitle: "Would you rather move forward now?",
      directText: "Open a new message directly in Gmail or use whichever email app you prefer. The guided diagnostic below captures business context without asking you for a technical specification.",
      directAction: "Open in Gmail",
      directFallbackAction: "Use another email app",
      directSubject: "Inquiry from Alejandro Fink's portfolio",
      directBody: "Hi Alejandro,\n\nI would like to discuss a project.",
      formEyebrow: "Initial diagnostic · 10 steps",
      statusLabel: "Contact status",
      enabledStatus: "Form active",
      disabledStatus: "Diagnostic active · Submission pending",
    },
    privacy: {
      metaTitle: "Privacy — Alejandro Fink",
      metaDescription: "The current state of data processing, contact and measurement on this portfolio.",
      eyebrow: "Privacy · Current state",
      title: "The form uses only the data needed to reply. Analytics remains disabled.",
      updated: "Last updated: August 10, 2026.",
      sections: [
        { title: "Contact diagnostic", text: "You can complete the diagnostic without any answer leaving the screen. If you ultimately submit it, the data you entered is processed: primary goal, starting point, blockers, audience, desired action, brand traits, solutions of interest, current investment range —including the option not to disclose it—, timing, decision stage, name, email, optional company, optional URL, language and optional additional context. Your IP and browser information are not stored in the inquiry inbox." },
        { title: "Purpose and controller", text: "Alejandro Fink uses this data exclusively to receive, organize and respond to professional inquiries. You can contact him at alegfink@gmail.com." },
        { title: "Services and access", text: "The site sends the inquiry to a Google Apps Script application. It is recorded in a private Google Sheet and a notification is sent through Google Mail. Only Alejandro has operational access to this inbox." },
        { title: "Retention", text: "Inquiries are kept for no longer than 12 months from receipt and deleted earlier when they are no longer needed. Follow-up and deletion are handled manually." },
        { title: "Your choices", text: "You may request access, correction or deletion of an inquiry by writing to alegfink@gmail.com. You may also use direct email without completing the form." },
        { title: "Measurement", text: "A technical event contract exists, but no analytics provider is installed. Events, form content and personal data are not recorded by default." },
        { title: "Language preference", text: "The ES/EN choice is stored locally in the browser and in a functional cookie so the preference can be respected. It is not used for advertising or cross-site tracking." },
        { title: "External links", text: "Case studies may link to third-party sites. Their own practices and policies apply when you visit them." },
      ],
    },
    notFound: { eyebrow: "Error 404", title: "This page is not part of the journey.", text: "You can return home or explore all six projects." },
    footer: { note: "Business-minded web development.", privacy: "Privacy", language: "Language" },
  },
} as const satisfies Record<Locale, unknown>;

export type SiteCopy = (typeof siteCopy)[Locale];
