import type { Locale } from "@/lib/i18n";

export const siteCopy = {
  es: {
    descriptor: "Desarrollador web y creador de productos digitales",
    skip: "Saltar al contenido",
    nav: { work: "Proyectos", services: "Servicios", about: "Sobre mí", contact: "Contacto", menu: "Abrir menú" },
    common: {
      viewProject: "Ver proyecto",
      viewAll: "Ver los seis proyectos",
      visit: "Visitar proyecto",
      next: "Siguiente proyecto",
      role: "Mi rol",
      state: "Estado",
      year: "Fecha",
      stack: "Tecnología relevante",
      limits: "Estado y límites",
      outcomes: "Resultado verificable",
      decisions: "Decisiones clave",
      solution: "Qué construí",
      problem: "El punto de partida",
      evidence: "Evidencia del trabajo",
      contact: "Contame tu proyecto",
      backHome: "Volver al inicio",
    },
    home: {
      metaTitle: "Alejandro Fink — Desarrollo web con criterio de negocio",
      metaDescription: "Sitios web, e-commerce y productos digitales diseñados y construidos para resolver necesidades reales de negocio.",
      eyebrow: "Desarrollo web · UX · Producto",
      title: "Diseño y desarrollo sitios web y productos digitales que resuelven problemas reales de negocio.",
      intro: "Combino desarrollo, experiencia de usuario y criterio comercial para convertir ideas, operaciones y oportunidades en soluciones web funcionales.",
      primaryCta: "Contame tu proyecto",
      secondaryCta: "Ver proyectos",
      signal: "De la necesidad a una primera versión útil — con criterio, ejecución y límites claros.",
      featuredEyebrow: "Trabajo seleccionado · 01–03",
      featuredTitle: "Una promesa es más útil cuando la prueba está cerca.",
      featuredIntro: "Tres proyectos en distintos momentos: un negocio propio en producción, una solución operativa y un MVP de validación.",
      servicesEyebrow: "Qué puedo construir · 04 frentes",
      servicesTitle: "La tecnología empieza después de entender qué necesita cambiar.",
      processEyebrow: "Cómo trabajo",
      processTitle: "Primero claridad. Después, una solución que se pueda usar.",
      processNote: "Uso IA para acelerar investigación, prototipado, desarrollo e iteración. La estrategia, el criterio y la validación siguen siendo humanos.",
      moreEyebrow: "Más trabajo · 04–06",
      moreTitle: "Funnel, high-ticket y una dirección editorial más humana.",
      perspectiveEyebrow: "Perspectiva",
      perspectiveTitle: "Construyo con la mirada de quien también vende y opera.",
      perspectiveText: "Mi base full stack se cruza con experiencia en ventas consultivas, UX, producto y desarrollo asistido por IA. Operar Torvena sumó una capa decisiva: convivir con catálogo, adquisición, soporte, logística y mejora continua, no solo con la interfaz.",
      closingTitle: "¿Hay una necesidad de negocio que una mejor experiencia web podría destrabar?",
      closingText: "Podemos ordenar el problema, definir una primera versión útil y decidir qué vale la pena construir ahora.",
    },
    services: [
      { number: "01", title: "Sitios de negocio y landing pages", text: "Clarificar una oferta, organizar el recorrido y convertir atención en una próxima acción concreta." },
      { number: "02", title: "E-commerce y experiencias de venta", text: "Conectar catálogo, contenido, confianza y operación dentro de un canal de venta propio." },
      { number: "03", title: "MVPs y productos digitales", text: "Transformar una oportunidad en una primera versión que permita observar uso, intención y límites reales." },
      { number: "04", title: "Soluciones a medida y evolución", text: "Extender productos existentes con flujos, paneles, integraciones y mejoras apoyadas en evidencia." },
    ],
    process: [
      { number: "01", title: "Entender", text: "Negocio, audiencia, restricciones y objetivo antes de elegir la forma de la solución." },
      { number: "02", title: "Definir", text: "Alcance, recorrido, contenido y una primera versión útil que se pueda validar." },
      { number: "03", title: "Diseñar y construir", text: "Interfaz, desarrollo e integraciones trabajando como un solo sistema." },
      { number: "04", title: "Validar y evolucionar", text: "QA, medición y aprendizaje cuando el proyecto y la operación lo permiten." },
    ],
    workIndex: {
      metaTitle: "Proyectos — Alejandro Fink",
      metaDescription: "Seis proyectos de e-commerce, servicios, MVP, conversión y dirección editorial, con estado y límites explícitos.",
      eyebrow: "Archivo de trabajo · Seis proyectos",
      title: "Contextos distintos. La misma forma de unir negocio, experiencia y ejecución.",
      intro: "Los casos están ordenados por realidad operativa, amplitud de decisiones y evidencia disponible. Cada uno declara su estado sin confundir un prototipo público con un producto en producción.",
      closing: "¿Tu proyecto no entra en una categoría prolija? Mejor: empecemos por el problema.",
    },
    about: {
      metaTitle: "Sobre mí — Alejandro Fink",
      metaDescription: "Cómo Alejandro Fink combina desarrollo, UX, experiencia comercial y operación para construir soluciones web útiles.",
      eyebrow: "Sobre mí",
      title: "Entender el negocio cambia lo que vale la pena construir.",
      lead: "Soy desarrollador web y creador de productos digitales. Mi trabajo vive en el cruce entre construcción técnica, experiencia de usuario y criterio comercial.",
      paragraphs: [
        "La formación full stack me dio una base para convertir decisiones en sistemas funcionales. La experiencia en ventas consultivas me enseñó a escuchar mejor el problema, detectar objeciones y no confundir una feature con una razón para comprar.",
        "UX, producto y desarrollo asistido por IA ampliaron ese proceso. Uso las herramientas para investigar, prototipar y construir con más alcance, mientras mantengo el criterio, la validación y la responsabilidad sobre lo que se publica.",
        "Torvena terminó de volver esta mirada operativa: además de construir el storefront, trabajo con catálogo, oferta, campañas, soporte, logística y mejora continua. Esa cercanía con la operación influye en cada solución que diseño.",
      ],
      principlesTitle: "Principios de trabajo",
      principles: ["Claridad sobre decoración.", "Negocio sobre tecnología.", "Evidencia sobre claims.", "Una primera versión útil sobre complejidad anticipada."],
      collaborationTitle: "Dónde puedo aportar",
      collaborationText: "Proyectos directos con dueños y equipos de negocio, colaboración con agencias o consultoras, y trabajo contract cuando el desafío requiere autonomía de producto y ejecución web.",
      photoNote: "El sitio funciona sin retrato personal hasta contar con material definitivo.",
    },
    contact: {
      metaTitle: "Contacto — Alejandro Fink",
      metaDescription: "Contale a Alejandro el contexto de tu sitio, e-commerce, MVP o producto digital.",
      eyebrow: "Contacto",
      title: "Empecemos por el contexto, no por una lista de features.",
      intro: "Contame qué necesita cambiar, quién lo usa y qué ya existe. Con eso podemos decidir si conviene una landing, un e-commerce, un MVP o una evolución a medida.",
      fitTitle: "Este espacio sirve para",
      fit: ["sitios de negocio y landing pages", "e-commerce y experiencias de venta", "MVPs y productos digitales", "evolución de productos existentes", "colaboraciones con agencias o equipos contract"],
      disabledTitle: "El canal todavía no está habilitado",
      disabledText: "La interfaz está preparada, pero el proveedor y el email de recepción aún no fueron configurados. Por eso los campos están desactivados y este sitio no envía ni almacena mensajes.",
      disabledAction: "Falta configurar un canal real antes de publicar.",
      fields: { name: "Nombre", company: "Empresa o proyecto (opcional)", email: "Email", need: "Tipo de necesidad", message: "Contexto del proyecto", submit: "Enviar consulta" },
      needs: { "business-site": "Sitio o landing", ecommerce: "E-commerce", product: "MVP o producto digital", evolution: "Evolución de un producto", collaboration: "Agencia o contract" },
      privacy: "Al enviar, aceptás el tratamiento descripto en la política de privacidad.",
      success: "Tu consulta fue entregada.",
      providerError: "No pudimos entregar la consulta. El contenido sigue en el formulario para que puedas reintentar.",
    },
    privacy: {
      metaTitle: "Privacidad — Alejandro Fink",
      metaDescription: "Estado real del tratamiento de datos, contacto y medición en este portfolio.",
      eyebrow: "Privacidad · Estado actual",
      title: "Este portfolio no recolecta mensajes ni activa analytics por defecto.",
      updated: "Última actualización: 8 de agosto de 2026.",
      sections: [
        { title: "Formulario de contacto", text: "Mientras no exista un proveedor y un email de recepción reales, el formulario permanece desactivado. Los campos no se envían, almacenan ni procesan." },
        { title: "Medición", text: "Existe un contrato técnico de eventos, pero no hay un proveedor de analytics instalado. No se registran eventos, contenido de formularios ni datos personales por defecto." },
        { title: "Preferencia de idioma", text: "La elección ES/EN se guarda localmente en el navegador y en una cookie funcional para respetar la preferencia. No se utiliza para publicidad ni seguimiento entre sitios." },
        { title: "Enlaces externos", text: "Los casos pueden enlazar a sitios de terceros. Al visitarlos, sus propias prácticas y políticas pasan a aplicar." },
        { title: "Antes de publicar", text: "Esta página debe actualizarse con el proveedor real, finalidad, datos tratados, responsable, retención, acceso y mecanismo de contacto antes de habilitar el formulario o analytics." },
      ],
    },
    notFound: { eyebrow: "Error 404", title: "Esta página no forma parte del recorrido.", text: "Podés volver al inicio o recorrer los seis proyectos." },
    footer: { note: "Desarrollo web con criterio de negocio.", privacy: "Privacidad", language: "Idioma" },
  },
  en: {
    descriptor: "Web Developer & Digital Product Builder",
    skip: "Skip to content",
    nav: { work: "Work", services: "Services", about: "About", contact: "Contact", menu: "Open menu" },
    common: {
      viewProject: "View project",
      viewAll: "View all six projects",
      visit: "Visit project",
      next: "Next project",
      role: "My role",
      state: "Status",
      year: "Date",
      stack: "Relevant technology",
      limits: "Current status and limits",
      outcomes: "Verified outcome",
      decisions: "Key decisions",
      solution: "What I built",
      problem: "The starting point",
      evidence: "Evidence of the work",
      contact: "Tell me about your project",
      backHome: "Back home",
    },
    home: {
      metaTitle: "Alejandro Fink — Business-minded web development",
      metaDescription: "Websites, e-commerce experiences and digital products designed and built to solve real business needs.",
      eyebrow: "Web development · UX · Product",
      title: "I design and build websites and digital products that solve real business problems.",
      intro: "I combine development, user experience, and commercial thinking to turn ideas, operations, and opportunities into functional web solutions.",
      primaryCta: "Tell me about your project",
      secondaryCta: "View my work",
      signal: "From a business need to a useful first version — with judgment, execution and clear limits.",
      featuredEyebrow: "Selected work · 01–03",
      featuredTitle: "A promise becomes useful when the proof is close by.",
      featuredIntro: "Three projects at different stages: an owned business in production, an operational solution and a validation MVP.",
      servicesEyebrow: "What I can build · 04 fronts",
      servicesTitle: "Technology comes after understanding what needs to change.",
      processEyebrow: "How I work",
      processTitle: "Clarity first. Then a solution people can actually use.",
      processNote: "I use AI to accelerate research, prototyping, development and iteration. Strategy, judgment and validation remain human.",
      moreEyebrow: "More work · 04–06",
      moreTitle: "Funnels, high-ticket offers and a more human editorial direction.",
      perspectiveEyebrow: "Perspective",
      perspectiveTitle: "I build with the perspective of someone who also sells and operates.",
      perspectiveText: "My full-stack foundation overlaps with consultative sales, UX, product and AI-assisted development. Operating Torvena added a decisive layer: working with catalog, acquisition, support, logistics and continuous improvement — not only the interface.",
      closingTitle: "Could a better web experience unlock a real business need?",
      closingText: "We can frame the problem, define a useful first version and decide what is worth building now.",
    },
    services: [
      { number: "01", title: "Business websites and landing pages", text: "Clarify an offer, shape the journey and turn attention into a concrete next step." },
      { number: "02", title: "E-commerce and sales experiences", text: "Connect catalog, content, trust and operations inside an owned sales channel." },
      { number: "03", title: "MVPs and digital products", text: "Turn an opportunity into a first version that can reveal usage, intent and real constraints." },
      { number: "04", title: "Custom solutions and product evolution", text: "Extend existing products with flows, dashboards, integrations and evidence-led improvements." },
    ],
    process: [
      { number: "01", title: "Understand", text: "Business, audience, constraints and goal before choosing the shape of the solution." },
      { number: "02", title: "Define", text: "Scope, journey, content and a useful first version that can be validated." },
      { number: "03", title: "Design and build", text: "Interface, development and integrations working as one system." },
      { number: "04", title: "Validate and evolve", text: "QA, measurement and learning when the project and operation make it possible." },
    ],
    workIndex: {
      metaTitle: "Work — Alejandro Fink",
      metaDescription: "Six e-commerce, service, MVP, conversion and editorial projects, each with explicit status and limits.",
      eyebrow: "Work archive · Six projects",
      title: "Different contexts. The same way of connecting business, experience and execution.",
      intro: "Projects are ordered by operational reality, breadth of decisions and available evidence. Each declares its status without mistaking a public prototype for a production product.",
      closing: "Does your project resist a neat category? Good — let’s start with the problem.",
    },
    about: {
      metaTitle: "About — Alejandro Fink",
      metaDescription: "How Alejandro Fink combines development, UX, commercial experience and operations to build useful web solutions.",
      eyebrow: "About",
      title: "Understanding the business changes what is worth building.",
      lead: "I’m a web developer and digital product builder. My work sits at the intersection of technical execution, user experience and commercial thinking.",
      paragraphs: [
        "A full-stack foundation gave me the means to turn decisions into functional systems. Consultative sales taught me to listen more closely to the problem, recognize objections and avoid confusing a feature with a reason to buy.",
        "UX, product thinking and AI-assisted development expanded that process. I use the tools to research, prototype and build with greater range while retaining judgment, validation and responsibility for what gets published.",
        "Torvena made this perspective operational: beyond the storefront, I work with catalog, offers, campaigns, support, logistics and continuous improvement. That proximity to the operation shapes every solution I design.",
      ],
      principlesTitle: "Working principles",
      principles: ["Clarity over decoration.", "Business over technology.", "Evidence over claims.", "A useful first version over anticipated complexity."],
      collaborationTitle: "Where I can contribute",
      collaborationText: "Direct projects with owners and business teams, collaboration with agencies or consultancies, and contract work when the challenge calls for product autonomy and web execution.",
      photoNote: "The site remains complete without a personal portrait until definitive material exists.",
    },
    contact: {
      metaTitle: "Contact — Alejandro Fink",
      metaDescription: "Share the context behind your website, e-commerce, MVP or digital product with Alejandro.",
      eyebrow: "Contact",
      title: "Let’s start with context, not a feature list.",
      intro: "Tell me what needs to change, who uses it and what already exists. From there, we can decide whether the right answer is a landing page, e-commerce experience, MVP or custom evolution.",
      fitTitle: "This space is for",
      fit: ["business websites and landing pages", "e-commerce and sales experiences", "MVPs and digital products", "evolution of existing products", "agency and contract collaborations"],
      disabledTitle: "The contact channel is not live yet",
      disabledText: "The interface is ready, but a provider and receiving email have not been configured. The fields are therefore disabled and this site does not send or store messages.",
      disabledAction: "A real channel must be configured before publication.",
      fields: { name: "Name", company: "Company or project (optional)", email: "Email", need: "Type of need", message: "Project context", submit: "Send inquiry" },
      needs: { "business-site": "Website or landing page", ecommerce: "E-commerce", product: "MVP or digital product", evolution: "Product evolution", collaboration: "Agency or contract" },
      privacy: "By sending, you agree to the processing described in the privacy notice.",
      success: "Your inquiry was delivered.",
      providerError: "We could not deliver your inquiry. Your content remains in the form so you can try again.",
    },
    privacy: {
      metaTitle: "Privacy — Alejandro Fink",
      metaDescription: "The current state of data processing, contact and measurement on this portfolio.",
      eyebrow: "Privacy · Current state",
      title: "This portfolio does not collect messages or enable analytics by default.",
      updated: "Last updated: August 8, 2026.",
      sections: [
        { title: "Contact form", text: "Until a real provider and receiving email exist, the form remains disabled. Fields are not sent, stored or processed." },
        { title: "Measurement", text: "A technical event contract exists, but no analytics provider is installed. Events, form content and personal data are not recorded by default." },
        { title: "Language preference", text: "The ES/EN choice is stored locally in the browser and in a functional cookie so the preference can be respected. It is not used for advertising or cross-site tracking." },
        { title: "External links", text: "Case studies may link to third-party sites. Their own practices and policies apply when you visit them." },
        { title: "Before publication", text: "This page must be updated with the real provider, purpose, data processed, controller, retention, access and contact mechanism before enabling the form or analytics." },
      ],
    },
    notFound: { eyebrow: "Error 404", title: "This page is not part of the journey.", text: "You can return home or explore all six projects." },
    footer: { note: "Business-minded web development.", privacy: "Privacy", language: "Language" },
  },
} as const satisfies Record<Locale, unknown>;

export type SiteCopy = (typeof siteCopy)[Locale];
